# Wrapper to run high resolution data fetch & map generation.
setwd("/home/snowreports/R/weather/")
cat("* Fetching HR data for 18Z forecast.")
sink("/dev/null")
system("export TZ=UTC")
source("01-get_hr_data_18.R")
sink(type="output")
cat("* Generating HR forecast map.")
sink("/dev/null")
gc()
source("02-map_hr_data.R")
rm(list=ls())
gc()
sink(type="output")
cat("* Generating Local forecasts.")
sink("/dev/null")
rm(list=ls())
gc()
source("05-get_hr_local.R")
system("export TZ=America/Vancouver")
sink(type="output")
cat("* Done.")
