# Wrapper to run low resolution data fetch & map generation.
setwd("/home/snowreports/R/weather/")
cat("* Fetching LR data for 00Z forecast.")
sink(NULL)
system("export TZ=UTC")
source("03-get_lr_data_00.R")
sink(type="output")
cat("* Generating LR forecast map.")
sink(NULL)
gc()
source("04-map_lr_data.R")
rm(list=ls())
gc()
source("06-get_lr_local.R")
system("export TZ=America/Vancouver")
sink(type="output")
cat("* Done.")
